# Generated by Django 5.0.6 on 2024-06-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_broadwaystudent_student_class'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadwayteacher',
            name='teacher_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentclass'),
        ),
    ]
