# Generated by Django 5.0.6 on 2024-06-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_broadwayteacher_teacher_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadwayteacher',
            old_name='teacher_name',
            new_name='Class_name',
        ),
    ]
