# Generated by Django 5.0.6 on 2024-06-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='class_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='class_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='class type'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
