# Generated by Django 5.0.6 on 2024-06-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentclass_class_link_studentclass_class_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
