# Generated by Django 5.0.6 on 2024-06-18 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentclass_created_at_studentclass_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadwaystudent',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentclass'),
        ),
    ]
